Allow to insert qt includes as external/system include.
dcourtois/premake-qt pull request #24
Opened 2023-02-23 15:12 UTC by Jarod42

Similar to https://github.com/dcourtois/premake-qt/pull/4
Notice that premake has renamed `sysincludedirs` into `externalincludedirs` since above PR. (from gcc-like name to msvc one).

As you ask an option, I add one (not sure about the name though)

Qt headers might (and currently does) generate warnings.
marked them as system/external header allows to ignore those warnings.

2023-02-24 08:41 UTC, ix-dcourtois commented
Just made a few notes (sorry for being nitpicky :))
Also, could you please update the Readme.md file to include the new option?

2023-02-24 12:51 UTC, Jarod42 commented
It seems you forget to send the notes ;-)

Indeed I forget Readme.md, I will do it.

2023-02-24 13:14 UTC, ix-dcourtois commented
By notes, I meant the review: I annotated the commits, it should be visible in this thread.

2023-02-24 17:01 UTC, dcourtois commented
Hmmm nope, it's not that...
For some reason, in this account I can't see the review that I started with my work account... and with my work account the annotations I added are marked "pending"...
Normally there should be a sort of "review" somewhere, but I'm not sure...

2023-02-24 17:04 UTC, ix-dcourtois requested changes
Ok, apparently I have to review my own annotation, so let's hope this works...

2023-02-24 17:09 UTC, Jarod42 commented on _preload.lua
> +-- Use external or regular include dir for Qt include path
Ok, now I see your comment. I will do it tonight I think

2023-02-24 17:38 UTC, Jarod42 commented on qt.lua
> +	end
Changed (but without the intermediate variable).

2023-02-24 17:39 UTC, Jarod42 commented on qt.lua
> +
Changed.

2023-02-24 17:39 UTC, Jarod42 commented on qt.lua
> +
Same as above too ;-)

2023-02-24 17:46 UTC, Jarod42 commented
Readme updated too.

2023-02-27 10:23 UTC, dcourtois commented
Added 2 comments (sorry, I have some OCDs :p)
And when it's done, you can squash those commits into 1 single commit with a clean message, force push, and I'll merge it :)

2023-02-27 14:02 UTC, Jarod42 commented
It seems it is again pending comments :)

2023-02-28 15:04 UTC, dcourtois reviewed
Gaaah, one day I'll get the hang of it...

2023-02-28 16:50 UTC, Jarod42 commented on Readme.md
> +##### qtuseexternalinclude(boolean_value)
Fixed.

2023-02-28 16:50 UTC, Jarod42 commented on Readme.md
> +		qtuseexternalinclude(true)
Fixed.

2023-03-01 08:37 UTC, merged